name: 'Run on Archlinuxarm'
branding:
  icon: 'cpu'
  color: 'green'
description: 'Run commands in a Linux container with a specific CPU architecture (armv6, armv7, aarch64, s390x, ppc64le)'
author: 'Umberto Raimondi, Elijah Shaw-Rutschman'
inputs:
  arch:
    description: 'CPU architecture: armv6, armv7, aarch64, s390x, ppc64le.'
    required: false
    default: 'aarch64'
  distro:
    description: 'Linux distribution name: ubuntu16.04, ubuntu18.04, ubuntu20.04, buster, stretch, jessie, fedora_latest, alpine_latest.'
    required: false
    default: 'archlinuxarm'
  githubToken:
    description: 'Your GitHub token, used for caching Docker images in your project''s public package registry. Usually this would just be $\{{ github.token }}. This speeds up builds and is highly recommended.'
    required: true
    default: ''
  env:
    description: 'Environment variables to propagate to the container. YAML, but must begin with a | character. These variables will be available in both run and setup.'
    required: false
    default: ''
  run:
    description: 'Shell commands to execute in the container.'
    required: false
    default: ''
  shell:
    description: 'The shell to run commands with in the container. Default: /bin/sh on alpine (because Alpine uses BusyBox), /bin/bash for other distros.'
    required: false
    default: ''
  dockerRunArgs:
    description: 'Additional arguments to pass to docker run, such as volume mappings. See README for example usage.'
    required: false
  setup:
    description: 'Shell commands to execute on the host before running the container, such as creating directories for volume mappings. See README for example usage.'
    required: false
    default: ''
  install:
    description: 'Shell commands to execute in the container as part of docker build, such as installing dependencies. This speeds up subsequent builds if githubToken is also used, but note that the image layer will be publicly available in your projects GitHub Package Registry, so make sure the resulting image does not have any secrets cached in logs or state.'
    required: false
    default: ''
  rcloneConfig:
    description: 'The content rclone config file.'
    required: true
    default: ''
  pgpKey:
    description: 'PGP private key used to Sign alarm package.'
    required: true
    default: ''
  pgpKeyPassword:
    description: 'The password of PGP private key.'
    required: true
    default: ''
  deployPath:
    description: 'The path to deploy archlinuxarm package. such as onedrive:mirrors/archlinuxarm/aarch64/core'
    required: true
    default: ''
  pacmanRepo:
    description: 'The repository to which the current archlinuxarm package belongs, such as core,community,extra.'
    required: true
    default: 'aur'
  customRepos:
    description: 'Custom package repositories to install packages via pacman, such as [aur]http://mirror.archlinuxarm.org/$arch/$repo. Use commas to separate multiple repositories.'
    required: false
    default: ''

runs:
  using: 'node12'
  main: 'src/run-on-arch.js'
