FROM archlinux/base:latest

RUN pacman-key --init
RUN pacman-key --populate archlinux

# Work-around the issue with glibc 2.33 on old Docker engines
# Extract files directly as pacman is also affected by the issue
RUN pacman --sync --refresh --sysupgrade --needed --noconfirm --disable-download-timeout glibc
RUN patched_glibc=glibc-linux4-2.33-5-x86_64.pkg.tar.zst && \
	curl -LO https://repo.archlinuxcn.org/x86_64/${patched_glibc} && \
	bsdtar -C / -xvf $patched_glibc
